Config = {
    "env": "PointMaze_UMaze-v3", 
    "warmup": 50,
    "batch_size": 64,
    "learning_rate": 0.001,
    "learning_rate_decay": 0.995,
    "alpha": 0.2,
    "gamma": 0.99,
    "tau": 0.005,
    "replay_buffer_size": int(1e6),
    "exploration_scaling_factor": 2.0,
    "episodes": 1000,
    "max_episode_steps": 300,
    "target_update_interval": 1,
    "updates_per_step": 4,
    "hidden_size": 256,
    "LOG_SIGN_MIN": -2,
    "LOG_SIGN_MAX": 20,
    "epsilon": 1e-6,
    "use_prioritized_replay": True,
    "prioritized_replay_alpha": 0.6,
    "prioritized_replay_beta": 0.4,
    "curriculum_learning": True,
    "curriculum_steps": [100, 500, 1000, 1500],
    "curriculum_difficulties": [0.3, 0.5, 0.7, 1.0]
}

